[package]
authors = ["Alula"]
edition = "2018"
name = "doukutsu-rs"
version = "0.1.0"

[lib]
crate-type = ["lib", "cdylib"]

[package.metadata.android]
android_version = 28
target_sdk_version = 28
min_sdk_version = 26
build_targets = ["aarch64-linux-android"]
package_name = "io.github.doukutsu_rs.android"
apk_label = "doukutsu-rs"
opengles_version = [2, 0]
fullscreen = true
orientation = "sensorLandscape"
permission = [
    {name = "android.permission.MANAGE_EXTERNAL_STORAGE"},
    {name = "android.permission.READ_EXTERNAL_STORAGE"},
    {name = "android.permission.WRITE_EXTERNAL_STORAGE"}
]
application_metadatas = [
    {name = "android:hardwareAccelerated", value = "true"},
    {name = "android:requestLegacyExternalStorage", value = "true"}
]

[profile.release]
lto = 'thin'
panic = 'abort'

[profile.dev.package."*"]
opt-level = 3

[profile.dev.build-override]
opt-level = 1

[profile.release.build-override]
opt-level = 1

[dependencies]
#cpal = {path = "./3rdparty/cpal"}
#gfx_device_gl = {path = "./3rdparty/gfx/src/backend/gl"}
#ggez = {path = "./3rdparty/ggez"}
#glutin = {path = "./3rdparty/glutin/glutin"}

bitvec = "0.17.4"
byteorder = "1.3"
case_insensitive_hashmap = "1.0.0"
chrono = "0.4"
cpal = {git = "https://github.com/doukutsu-rs/cpal.git", branch = "android-support"}
directories = "2"
gfx = "0.18"
gfx_core = "0.9"
gfx_device_gl = {git = "https://github.com/doukutsu-rs/gfx.git", branch = "pre-ll"}
ggez = {git = "https://github.com/doukutsu-rs/ggez.git", rev = "d70d3f059077efde7cae02f37e7b077924880128"}
gilrs = "0.8"
glutin = {git = "https://github.com/doukutsu-rs/glutin.git", branch = "android-support"}
imgui = {git = "https://github.com/Gekkio/imgui-rs.git", rev = "a990a538b66cb67dba3a072bf299b6a51c001447"}
imgui-gfx-renderer = {git = "https://github.com/Gekkio/imgui-rs.git", rev = "a990a538b66cb67dba3a072bf299b6a51c001447"}
imgui-winit-support = {git = "https://github.com/Gekkio/imgui-rs.git", default-features = false, features = ["winit-23"], rev = "a990a538b66cb67dba3a072bf299b6a51c001447"}
image = {version = "0.22", default-features = false, features = ["png_codec", "pnm", "bmp"]}
itertools = "0.9.0"
lazy_static = "1.4.0"
log = "0.4"
lru = "0.6.0"
num-derive = "0.3.2"
num-traits = "0.2.12"
paste = "1.0.0"
pretty_env_logger = "0.4.0"
serde = {version = "1", features = ["derive"]}
serde_derive = "1"
serde_yaml = "0.8"
strum = "0.18.0"
strum_macros = "0.18.0"
# remove and replace when drain_filter is in stable
vec_mut_scan = "0.3.0"
webbrowser = "0.5.5"
winit = {version = "0.23.0", features = ["serde"]}

[target.'cfg(target_os = "android")'.dependencies]
ndk = "0.2.0"
ndk-glue = "0.2.0"
jni = "0.17"
